### ISSUE TITLE
Add SSL

### ISSUE THREAD

**Issue by dtrodrigues** [mkayen/CouchMVP#8]
Configure the site to use SSL

**Comment by mkayen** [comment]
What was it using before??

On Sun, Aug 31, 2014 at 9:05 PM, Dustin Rodrigues notifications@github.com
wrote:

> Configure the site to use SSL
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mkayen/CouchMVP/issues/8.

## 

Max Kayen
(516 375 5270)
mkayen@gmail.com

**Comment by dtrodrigues** [comment]
It's just using plain HTTP now.
