### ISSUE TITLE
Custom Sign in/up forms

### ISSUE THREAD

**Issue by dtrodrigues** [mkayen/CouchMVP#9]
Use the forms from the template instead of the standard devise forms.

**Comment by mkayen** [comment]
Agree - First the Login Form, then the Sign Up

**Comment by mkayen** [comment]
Hey - I think we are good to push the most recent pull request. Lemme know
if you can merge.

Thx,Max

On Sun, Aug 31, 2014 at 9:10 PM, Dustin Rodrigues notifications@github.com
wrote:

> Assigned #9 https://github.com/mkayen/CouchMVP/issues/9 to @mkayen
> https://github.com/mkayen.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mkayen/CouchMVP/issues/9#event-159439474.

## 

Max Kayen
(516 375 5270)
mkayen@gmail.com

**Comment by dtrodrigues** [comment]
closed this issue since it's partially done. will open a new issue for sign up form
